server {
    listen 80;
    server_name _;
    
    root /usr/share/nginx/html;
    
    location / {
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
        autoindex_format html;
        # autoindex_ignore "#*.jsonl";
        
        # Forhindre caching
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
        
        # CORS hvis eleverne skal tilgå fra andre domæner
        add_header Access-Control-Allow-Origin *;
    }
    
    location ~ \.jsonl$ {
        # Vis .jsonl filer som tekst i browseren
        types {
            text/plain jsonl;
        }
        
        charset utf-8;
        
        # Forhindre download, vis i stedet i browseren
        add_header Content-Disposition "inline";
        
        # Forhindre caching
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}